
-- Додавання відсутніх колонок у brands
ALTER TABLE "brands"
ADD COLUMN IF NOT EXISTS "logo" TEXT,
ADD COLUMN IF NOT EXISTS "description" TEXT,
ADD COLUMN IF NOT EXISTS "website" TEXT,
ADD COLUMN IF NOT EXISTS "country" TEXT;

-- Додавання відсутніх колонок у tyres
ALTER TABLE "tyres"
ADD COLUMN IF NOT EXISTS "title" TEXT,
ADD COLUMN IF NOT EXISTS "description" TEXT,
ADD COLUMN IF NOT EXISTS "country" VARCHAR(50),
ADD COLUMN IF NOT EXISTS "date_code" CHAR(4),
ADD COLUMN IF NOT EXISTS "applicability" VARCHAR(50),
ADD COLUMN IF NOT EXISTS "sku" VARCHAR(50) NOT NULL,
ADD COLUMN IF NOT EXISTS "inventory_quantity" INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS "price" DECIMAL(10,2) NOT NULL,
ADD COLUMN IF NOT EXISTS "load_speed_index" VARCHAR(10),
ADD COLUMN IF NOT EXISTS "brand" VARCHAR(50),
ADD COLUMN IF NOT EXISTS "model" VARCHAR(100),
ADD COLUMN IF NOT EXISTS "type" VARCHAR(50),
ADD COLUMN IF NOT EXISTS "load_index" VARCHAR(10),
ADD COLUMN IF NOT EXISTS "speed_index" VARCHAR(10),
ADD COLUMN IF NOT EXISTS "constr" VARCHAR(10),
ADD COLUMN IF NOT EXISTS "width" INTEGER,
ADD COLUMN IF NOT EXISTS "profile" INTEGER,
ADD COLUMN IF NOT EXISTS "diameter" INTEGER,
ADD COLUMN IF NOT EXISTS "delimiter" VARCHAR(10),
ADD COLUMN IF NOT EXISTS "brand_id" INTEGER REFERENCES "brands"("id"),
ADD COLUMN IF NOT EXISTS "model_id" INTEGER;


-- Додавання унікального індексу для sku
CREATE UNIQUE INDEX IF NOT EXISTS "tires_sku_key" ON "tyres"("sku");

-- Додавання зовнішніх ключів
ALTER TABLE "tyres" ADD CONSTRAINT IF NOT EXISTS "tyres_model_id_fkey" 
FOREIGN KEY ("model_id") REFERENCES "models"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "tyres" ADD CONSTRAINT IF NOT EXISTS "tyres_brand_id_fkey" 
FOREIGN KEY ("brand_id") REFERENCES "brands"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "models" ADD CONSTRAINT IF NOT EXISTS "models_brandId_fkey" 
FOREIGN KEY ("brandId") REFERENCES "brands"("id") ON DELETE CASCADE ON UPDATE CASCADE;
