name: Deploy to VPS

on:
  push:
    branches:
      - main

env:
  SERVER_HOST: 38.242.214.198
  SERVER_USER: root
  PROJECT_DIR: /var/www/shina-mix-shop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -t rsa,ed25519 $SERVER_HOST >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh -i ~/.ssh/id_ed25519 $SERVER_USER@$SERVER_HOST << 'EOF'
            cd $PROJECT_DIR
            git pull origin main
            npm install --omit=dev
            npm run build
            pm2 restart shina-mix-shop
          EOF
